#!/usr/bin/python

target = "test"
ccflags = "-Wall -O3"
cc = "ccache g++ -std=c++11"

sources = [
	"test.cpp",
	"../src/crypto.cpp",
	"../src/mega.cpp",
]

libs = [
	"cryptopp",
	"gtest",
	"pthread",
	"cppnetlib-uri",
	"cppnetlib-client-connections",
	"boost_system",
	"boost_thread",
	"crypt",
	"ssl",
	"crypto",
	"jsoncpp",
]

env = Environment(CXX = cc)
env.Program(
	source = sources,
	target = target,
	CCFLAGS = ccflags,
	LIBS = libs,
)
